[project]
site_name = "VARS Annotation"
site_description = "VARS Annotation System"
site_author = "Brian Schlining"
repo_name = "mbari-org/vars-annotation"
repo_url = "https://github.com/mbari-org/vars-annotation"
nav = [
  { "Home" = "index.md" },
  { "Setup" = "setup.md" },
  { "Status Bar" = "statusbar.md" },
  { "MBARI Docs" = "https://docs.mbari.org" },
]

[project.theme]
name = "material"
logo = "assets/images/mbari-logo.png"
# favicon = "assets/images/favicon.ico"
features = [
    "navigation.instant",
    "navigation.indexes",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "toc.integrate",
    "content.code.copy",
    "search.highlight",
]
icon.repo = "lucide/github"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preferences"

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]