/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

import java.nio.file.FileSystems
import java.nio.file.Files

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("com.github.ben-manes.versions") version "0.53.0"
    id("com.adarshr.test-logger") version "4.0.0"
    id("org.beryx.jlink") version "3.2.1"
    id("org.gradlex.extra-java-module-info") version "1.14"
}

version = "2.3.0"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

javafx {
    version = "25.0.2"
    modules("javafx.base", "javafx.controls", "javafx.fxml", "javafx.graphics", "javafx.media", "javafx.swing")
}

repositories {
    mavenLocal()
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

//Resolve the used operating system
var currentOS = org.gradle.nativeplatform.platform.internal.DefaultNativePlatform.getCurrentOperatingSystem()
var platform = ""
if (currentOS.isMacOsX) {
    platform = "mac"
} else if (currentOS.isLinux) {
    platform = "linux"
} else if (currentOS.isWindows) {
    platform = "win"
}

configurations.all {
    // Exclude stax-api as javax.xml.stream is part of java.xml platform module
    exclude(group = "javax.xml.stream", module = "stax-api")
    exclude(group = "stax", module = "stax-api")
}

// Define versions in variables to avoid hardcoding them in multiple places and to make it easier to update them.
val annosaurusSdkVersion = "0.0.17"
val caffeineVersion = "3.1.8"
val configVersion = "1.4.5"
val controlsFxVersion = "11.2.3"
val gsonVerion = "2.13.2"
val ikonliVersion = "12.3.1"
val imgfxVersion = "0.0.17"
val jeromqVersion = "0.6.0"
val logbackVersion = "1.5.27"
val mbariCommonsVersion = "0.0.7"
val methanolVersion = "1.9.0"
val okhttpLoggingInterceptorVersion = "3.14.4"
val oniSdkVersion = "0.0.12"
val razielSdkVersion = "0.0.4"
val slf4jVersion = "2.0.17"
val swingxVersion = "1.6.5-1"
val vampireSquidSdkVersion = "0.0.14"
val vcr4jVersion = "5.3.1"



dependencies {

    // This has to match the okhttp version used in org.mbari.vars.services or
    // we get java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
//    implementation("com.squareup.okhttp3:okhttp:3.14.9")

    implementation("ch.qos.logback:logback-classic:${logbackVersion}")
    implementation("org.slf4j:slf4j-api:${slf4jVersion}")
    implementation("com.github.ben-manes.caffeine:caffeine:$caffeineVersion")
    implementation("com.github.mizosoft.methanol:methanol:$methanolVersion")
    implementation("com.google.code.gson:gson:$gsonVerion")
    implementation("com.squareup.okhttp3:logging-interceptor:$okhttpLoggingInterceptorVersion")
    implementation("com.typesafe:config:$configVersion")
    implementation("org.controlsfx:controlsfx:$controlsFxVersion")
    // IMPORTANT - ikonli version needs to be the same as the one used in imgfx or the icons won't render.
    implementation("org.kordamp.ikonli:ikonli-core:$ikonliVersion")
    implementation("org.kordamp.ikonli:ikonli-javafx:$ikonliVersion")
    implementation("org.kordamp.ikonli:ikonli-swing:$ikonliVersion")
    implementation("org.kordamp.ikonli:ikonli-material2-pack:$ikonliVersion")
    implementation("org.mbari.commons:jcommons:$mbariCommonsVersion")
    implementation("org.mbari.imgfx:imgfx:$imgfxVersion")
    implementation("org.mbari.vars:annosaurus-java-sdk:$annosaurusSdkVersion")
    implementation("org.mbari.vars:oni-java-sdk:$oniSdkVersion")
    implementation("org.mbari.vars:raziel-java-sdk:$razielSdkVersion")
    implementation("org.mbari.vars:vampire-squid-java-sdk:$vampireSquidSdkVersion")
    implementation("org.mbari.vcr4j:vcr4j-core:$vcr4jVersion")
    implementation("org.mbari.vcr4j:vcr4j-remote:$vcr4jVersion")
    implementation("org.swinglabs.swingx:swingx-all:$swingxVersion")
    implementation("org.zeromq:jeromq:$jeromqVersion")


    implementation("org.controlsfx:controlsfx:$controlsFxVersion") {
        exclude(group = "org.openjfx", module = "javafx-base")
        exclude(group = "org.openjfx", module = "javafx-controls")
        exclude(group = "org.openjfx", module = "javafx-graphics")
        because("If not excluded we end up with both mac and linux javafx jars which cause jlink to fail")
    }

    implementation("com.github.ben-manes.caffeine:caffeine:$caffeineVersion") {
        exclude(group = "org.checkerframework", module = "checker-qual")
    }

    // Gradle adds junit-platform-launcher to the test runtime but doesn't
    // resolve its version from the test suite's useJUnitJupiter() declaration
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.10.2")

//    implementation("ch.qos.logback:logback-classic:$logbackVersion") {
//        exclude(group = "javax.activation")
//    }
}

//tasks.withType<JavaExec>().configureEach {
//    // This helps Gradle understand that all dependencies should
//    // be treated as modules if they have a module-info or Automatic-Module-Name
//    modularity.inferModulePath = true
//}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.10.2")
        }

        // Integration test suite (replaces nebula.integtest plugin)
        register<JvmTestSuite>("integrationTest") {
            // Tests use JUnit Jupiter test framework
            useJUnitJupiter("5.10.2")
            sources {
                java {
                    srcDirs("src/integTest/java")
                }
                resources {
                    srcDirs("src/integTest/resources")
                }
            }
            dependencies {
                // Include main project and its dependencies
                implementation(project())
                // Explicitly add SDK dependencies for integration tests
                implementation("com.typesafe:config:$configVersion")
                implementation("org.mbari.vars:vampire-squid-java-sdk:$vampireSquidSdkVersion")
                implementation("org.mbari.vars:annosaurus-java-sdk:$annosaurusSdkVersion")
                implementation("org.mbari.vars:oni-java-sdk:$oniSdkVersion")
                implementation("org.mbari.vars:raziel-java-sdk:$razielSdkVersion")
                implementation("org.junit.platform:junit-platform-launcher:1.10.2")
                implementation("org.mbari.vcr4j:vcr4j-core:$vcr4jVersion")
                implementation("org.mbari.vcr4j:vcr4j-remote:$vcr4jVersion")
            }
            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(test)
                    }
                }
            }
        }
    }
}

tasks.named<Test>("test") {
    useJUnitPlatform()

    maxHeapSize = "1G"

    testLogging {
        events("passed")
    }

    // Disable module path for tests - Kiota has split packages that break JPMS
    modularity.inferModulePath.set(false)
}

// Configure automatic module names for JARs without Automatic-Module-Name in their manifest
extraJavaModuleInfo {
    failOnMissingModuleInfo.set(false)
    automaticModule("org.swinglabs.swingx:swingx-all", "swingx.all")
    // Note: Microsoft Kiota libraries have split packages and cannot be modularized.
    // They stay on the classpath automatically due to failOnMissingModuleInfo.set(false)
}

tasks.named<Test>("integrationTest") {
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }

    // Disable module path for tests - Kiota has split packages that break JPMS
    modularity.inferModulePath.set(false)
}

// JVM args for development (classpath mode)
val devJvmArgs = arrayListOf(
    "-Djdk.httpclient.HttpClient.log=requests,headers,content",
    "-XX:+TieredCompilation",
    "-XX:TieredStopAtLevel=1",
    "-Xms1g"
)

// JVM args for jpackaged application (uses merged module)
val runtimeJvmArgs = arrayListOf(
    "-Djdk.httpclient.HttpClient.log=requests,headers,content",
    "-XX:+TieredCompilation",
    "-XX:TieredStopAtLevel=1",
    "-Xms1g",
    "--enable-native-access=javafx.graphics",
    "--add-opens", "java.base/java.lang.invoke=vars.annotation.merged.module",
    "--add-reads", "vars.annotation.merged.module=org.slf4j",
    "--add-reads", "vars.annotation.merged.module=com.google.gson",
    "--add-reads", "vars.annotation.merged.module=java.logging",
    "--add-reads", "vars.annotation.merged.module=java.desktop"
)


application {
    // Define the main class for the application.
    // Note: Don't set mainModule - Kiota has split packages that break JPMS at runtime
    // The jpackage/jlink build uses mergedModule which handles this properly
    // AppLauncher avoids the "JavaFX runtime components are missing" error when
    // running on the classpath (i.e. modularity.inferModulePath = false)
    mainClass.set("org.mbari.vars.annotation.AppLauncher")
    if(platform.equals("mac")) {
        applicationDefaultJvmArgs = listOf("-Dsun.java2d.metal=true") + devJvmArgs
    } else {
        applicationDefaultJvmArgs = devJvmArgs
    }
}

// Disable module path for run task - Kiota has split packages that break JPMS
tasks.named<JavaExec>("run") {
    modularity.inferModulePath.set(false)
}

tasks.register<JavaExec>("runDebug") {
    description = "Run the application with debug enabled on port 5005"
    group = "application"
    mainClass.set("org.mbari.vars.annotation.AppLauncher")
    classpath = sourceSets["main"].runtimeClasspath
    // Disable module path - Kiota has split packages that break JPMS
    modularity.inferModulePath.set(false)
    jvmArgs = devJvmArgs + listOf(
        "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
    )
}

// Patch reactor-core jar to remove problematic service providers
// This runs before jlink processes dependencies
tasks.register("patchReactorCore") {
    doLast {
        val reactorJars = configurations.runtimeClasspath.get().files.filter {
            it.name.contains("reactor-core") && it.name.endsWith(".jar")
        }
        reactorJars.forEach { jarFile ->
            println("Patching ${jarFile.name} to remove optional service providers")
            val fs = FileSystems.newFileSystem(jarFile.toPath(), null as ClassLoader?)
            try {
                val servicesToRemove = listOf(
                    "META-INF/services/io.micrometer.context.ContextAccessor",
                    "META-INF/services/reactor.blockhound.integration.BlockHoundIntegration"
                )
                servicesToRemove.forEach { servicePath ->
                    val path = fs.getPath(servicePath)
                    if (Files.exists(path)) {
                        Files.delete(path)
                        println("  Removed $servicePath")
                    }
                }
            } finally {
                fs.close()
            }
        }
    }
}

tasks.named("createMergedModule") {
    dependsOn("patchReactorCore")
}

jlink {
    // Use the configured Java toolchain
    javaHome.set(project.javaToolchains.launcherFor(java.toolchain).get().metadata.installationPath.asFile)

    options.set(listOf("--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages", "--ignore-signing-information"))

    launcher {
        name = "VARS Annotation"
        jvmArgs = runtimeJvmArgs
    }

    mergedModule {
        additive = true

        // Add uses clauses for Azure and OpenTelemetry service loaders if needed at runtime
        uses("io.opentelemetry.context.ContextStorageProvider")
        uses("com.azure.core.util.tracing.Tracer")
        uses("com.azure.core.util.serializer.JsonSerializer")
        uses("com.azure.core.util.serializer.MemberNameConverter")
        uses("com.azure.core.http.policy.AfterRetryPolicyProvider")
        uses("com.azure.core.http.policy.BeforeRetryPolicyProvider")
        uses("org.jdesktop.swingx.plaf.LookAndFeelAddons")
    }

    jpackage {
        val customInstallerOptions = arrayListOf(
            "--app-version", project.version.toString(),
            "--copyright", "Monterey Bay Aquarium Research Institute 2023",
            "--name", "VARS Annotation",
            "--vendor", "org.mbari"
        )

        if (platform == "mac") {
            installerType = "dmg"
            customInstallerOptions.addAll(listOf(
                "--mac-package-name", "VARS Annotation",
                "--mac-package-identifier", project.name.toString()
            ))
            imageOptions = listOf("--icon", "src/jpackage/macos/VARS Annotation.icns")
        }
        else if (platform == "linux") {
            installerType = "deb"
            customInstallerOptions.addAll(listOf(
                "--linux-shortcut", "true",
                "--linux-menu-group", "VARS"
            ))
            imageOptions = listOf("--icon", "src/jpackage/linux/icon_256x256.png")
        }
        else if (platform == "win") {
            installerType = "msi"
            customInstallerOptions.addAll(listOf(
                "--win-upgrade-uuid", "1afa1e7b-8c54-4007-9ccb-537b61826967",
                "--win-menu-group", "VARS",
                "--win-menu"
            ))
            imageOptions = listOf("--icon", "src/jpackage/win/icon_256x256.ico")
        }
        installerOptions = customInstallerOptions
    }
}

tasks.jpackageImage.get().doLast {
    if (platform == "mac") {
        val signer = System.getenv("MAC_CODE_SIGNER")
        if (signer != null) {
            val dirsToBeSigned = arrayListOf(
                file("${projectDir}/build/jpackage/VARS Annotation.app/Contents/runtime/Contents/Home/bin"),
                file("${projectDir}/build/jpackage/VARS Annotation.app/Contents/runtime/Contents/Home/lib"),
                file("${projectDir}/build/jpackage/VARS Annotation.app/Contents/runtime/Contents/Home/lib/server"),
                file("${projectDir}/build/jpackage/VARS Annotation.app/Contents/runtime/Contents/MacOS")
            )

            val entitlements = "${projectDir}/src/jpackage/macos/java.entitlements"
            val jpackageDir = file("${projectDir}/build/jpackage")

            dirsToBeSigned.forEach { dir ->
                println("Signing $dir")
                val files = layout.files(dir.listFiles())
                files
                    .filter { it.isFile }
                    .forEach { f ->
                        println("MACOSX: Signing ${f}")
                        ProcessBuilder(listOf(
                            "codesign",
                            "--entitlements", entitlements,
                            "--options", "runtime",
                            "--timestamp",
                            "-vvv",
                            "-f",
                            "--sign", signer,
                            f.absolutePath
                        ))
                            .directory(jpackageDir)
                            .inheritIO()
                            .start()
                            .waitFor()
                    }
            }

            println("MACOSX: Signing application")
            ProcessBuilder(listOf(
                "codesign",
                "--entitlements", entitlements,
                "--options", "runtime",
                "--timestamp",
                "-vvv",
                "-f",
                "--sign", signer,
                "VARS Annotation.app"
            ))
                .directory(jpackageDir)
                .inheritIO()
                .start()
                .waitFor()
        }
    }
}