package org.mbari.m3.vars.annotation.ui.deployeditor;

import com.google.common.collect.Lists;
import io.reactivex.Observable;
import javafx.beans.InvalidationListener;
import javafx.beans.property.SimpleObjectProperty;
import javafx.collections.ObservableList;
import javafx.scene.control.*;
import org.mbari.m3.vars.annotation.EventBus;
import org.mbari.m3.vars.annotation.UIToolBox;

import org.mbari.m3.vars.annotation.commands.*;
import org.mbari.m3.vars.annotation.events.AnnotationsAddedEvent;
import org.mbari.m3.vars.annotation.events.AnnotationsChangedEvent;
import org.mbari.m3.vars.annotation.events.AnnotationsRemovedEvent;
import org.mbari.m3.vars.annotation.events.AnnotationsSelectedEvent;
import org.mbari.m3.vars.annotation.model.Annotation;
import org.mbari.m3.vars.annotation.services.MediaService;
import org.mbari.m3.vars.annotation.ui.shared.AnnotationTableViewFactory;
import org.mbari.m3.vars.annotation.util.AsyncUtils;
import org.mbari.m3.vars.annotation.util.JFXUtilities;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.URI;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.prefs.Preferences;
import java.util.stream.Collectors;

/**
 * @author Brian Schlining
 * @since 2018-04-05T15:00:00
 */
public class AnnotationTableController {

    private TableView<Annotation> tableView;
    private final ResourceBundle i18n;
    private final Map<UUID, URI> videoReferenceUriMap  = new ConcurrentHashMap<>();
    private final UIToolBox toolBox;

    private final Logger log = LoggerFactory.getLogger(getClass());

    public AnnotationTableController(UIToolBox toolBox, EventBus eventBus) {
        this.toolBox = toolBox;
        this.i18n = toolBox.getI18nBundle();

        Observable<Object> observable = eventBus.toObserverable();

        observable.ofType(AnnotationsAddedEvent.class)
                .subscribe(e -> JFXUtilities.runOnFXThread(() -> {
                    getTableView().getItems().addAll(e.get());
                    getTableView().sort();
                }));

        observable.ofType(AnnotationsRemovedEvent.class)
                .subscribe(e -> JFXUtilities.runOnFXThread(() ->
                        getTableView().getItems().removeAll(e.get())));

        // Listen for external selection events, but ignore ones generated by this controlle
        observable.ofType(AnnotationsSelectedEvent.class)
                .filter(e -> e.getEventSource() != AnnotationTableController.this )
                .filter(e -> !(e.getEventSource() instanceof org.mbari.m3.vars.annotation.ui.annotable.AnnotationTableController))
                .subscribe(e -> select(e.get()));

        observable.ofType(AnnotationsChangedEvent.class)
                .subscribe(e ->
                    JFXUtilities.runOnFXThread(() -> {
                        Collection<Annotation> annotations = e.get();
                        String message = "Redrawing " + annotations.size() +
                                " annotations:" +
                                annotations.stream()
                                    .map(Annotation::getConcept)
                                    .collect(Collectors.joining(", "));
                        log.debug(message);
                        ObservableList<Annotation> items = getTableView().getItems();
                        for (Annotation a : annotations) {
                            int idx = items.indexOf(a);
                            items.remove(idx);
                            items.add(idx, a);
                        }
                        tableView.refresh();
                        tableView.sort();
                        eventBus.send(new AnnotationsSelectedEvent(annotations));
                    }));

        // Forward this tables annotation mutating events to main event bus
        EventBus mainEventBus = toolBox.getEventBus();
        ArrayList<Class<? extends Command>> commandsToForward = Lists.newArrayList(ChangeGroupCmd.class,
                ChangeActivityCmd.class,
                MoveAnnotationsCmd.class,
                ChangeConceptCmd.class,
                DeleteAssociationsCmd.class);
        for (Class<? extends Command> clazz : commandsToForward) {
            observable.ofType(clazz)
                    .subscribe(mainEventBus::send);
        }

        // Load the column visibility and width
        loadPreferences();

        // After annotations are added do lookup of video URI for video URI column
        getTableView().getItems()
                .addListener((InvalidationListener) obs -> updateVideoReferenceUris());

    }

    private void select(Collection<Annotation> annos) {
        JFXUtilities.runOnFXThread(() -> {
            TableView.TableViewSelectionModel<Annotation> selectionModel = getTableView().getSelectionModel();
            selectionModel.clearSelection();
            annos.forEach(selectionModel::select);
        });
    }

    private void updateVideoReferenceUris() {
        ObservableList<Annotation> items = getTableView().getItems();
        List<UUID> uuids = items.stream()
                .map(Annotation::getVideoReferenceUuid)
                .distinct()
                .collect(Collectors.toList());

        Set<UUID> existingUuids = videoReferenceUriMap.keySet();

        List<UUID> newUuids = new ArrayList<>(uuids);
        newUuids.removeAll(existingUuids);

        if (newUuids.size() > 0) {
            videoReferenceUriMap.clear();
            MediaService mediaService = toolBox.getServices().getMediaService();
            AsyncUtils.collectAll(uuids, mediaService::findByUuid)
                    .thenAccept(medias ->
                            medias.forEach(m -> videoReferenceUriMap.put(m.getVideoReferenceUuid(), m.getUri())))
                    .thenAccept(v -> getTableView().refresh());
        }
    }


    private void loadPreferences() {
        // Load the column visibility and width
        Preferences prefs = Preferences.userNodeForPackage(getClass());
        Preferences columnPrefs = prefs.node("table-columns");
        getTableView().getColumns()
                .forEach(tc -> {
                    Preferences p = columnPrefs.node(tc.getId());
                    String s = p.get("visible", "true");
                    boolean isVisible = s.equals("true");
                    String w = p.get("width", "100");
                    double width = Double.parseDouble(w);
                    JFXUtilities.runOnFXThread(() -> {
                        tc.setVisible(isVisible);
                        tc.setPrefWidth(width);
                    });
                });

    }

    public void savePreferences() {
        Preferences prefs = Preferences.userNodeForPackage(getClass());
        Preferences columnPrefs = prefs.node("table-columns");
        getTableView().getColumns()
                .forEach(tc -> {
                    Preferences p = columnPrefs.node(tc.getId());
                    p.put("visible", "false");
                    p.put("width", tc.getWidth() + "");
                });
        getTableView().getVisibleLeafColumns()
                .forEach(tc -> {
                    Preferences p = columnPrefs.node(tc.getId());
                    p.put("visible", "true");
                });
    }

    public TableView<Annotation> getTableView() {
        if (tableView == null) {
            tableView = AnnotationTableViewFactory.newTableView(i18n);

            TableColumn<Annotation, URI> vruCol
                    = new TableColumn<>(i18n.getString("annotable.col.videoreference"));
            vruCol.setCellValueFactory(param -> {
                URI uri = null;
                if (param.getValue() != null) {
                    uri = videoReferenceUriMap.get(param.getValue().getVideoReferenceUuid());
                }
                return new SimpleObjectProperty<>(uri);
            });
            vruCol.setId("videoReferenceUuid");

            // TODO get column order from preferences
            tableView.getColumns().add(vruCol);

        }
        return tableView;
    }
}
